apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort  # Exposed via Ingress (not LoadBalancer)
  selector:
    app: survey-page-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30040

